version: '3'
services:
  # PostgreSQL Database
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
